export const ROOT_URL = 'https://dev-expenses-api.pantheonsite.io';

export const categories = [
  { value: '', label: 'Category' },
  { value: '1', label: 'Clothing' },
  { value: '2', label: 'Entertainment' },
  { value: '3', label: 'Food' },
  { value: '4', label: 'Gifts' },
  { value: '5', label: 'Household Items/Supplies' },
  { value: '6', label: 'Housing' },
  { value: '7', label: 'Medical / Healthcare' },
  { value: '8', label: 'Personal' },
  { value: '9', label: 'Transportation' },
  { value: '10', label: 'Utilities' },
  { value: '11', label: 'Travel' },
  { value: '12', label: 'Family' },
  { value: '13', label: 'Investment' },
];

export const monthNames = [
  'January',
  'February',
  'March',
  'April',
  'May',
  'June',
  'July',
  'August',
  'September',
  'October',
  'November',
  'December',
];

export const currencies = {
  AED: 'United Arab Emirates Dirham',
  AFN: 'Afghan Afghani',
  ALL: 'Albanian Lek',
  AMD: 'Armenian Dram',
  ANG: 'Netherlands Antillean Guilder',
  AOA: 'Angolan Kwanza',
  ARS: 'Argentine Peso',
  AUD: 'Australian Dollar',
  AWG: 'Aruban Florin',
  AZN: 'Azerbaijani Manat',
  BAM: 'Bosnia-Herzegovina Convertible Mark',
  BBD: 'Barbadian Dollar',
  BDT: 'Bangladeshi Taka',
  BGN: 'Bulgarian Lev',
  BHD: 'Bahraini Dinar',
  BIF: 'Burundian Franc',
  BMD: 'Bermudan Dollar',
  BND: 'Brunei Dollar',
  BOB: 'Bolivian Boliviano',
  BRL: 'Brazilian Real',
  BSD: 'Bahamian Dollar',
  BTC: 'Bitcoin',
  BTN: 'Bhutanese Ngultrum',
  BWP: 'Botswanan Pula',
  BYN: 'Belarusian Ruble',
  BZD: 'Belize Dollar',
  CAD: 'Canadian Dollar',
  CDF: 'Congolese Franc',
  CHF: 'Swiss Franc',
  CLF: 'Chilean Unit of Account (UF)',
  CLP: 'Chilean Peso',
  CNH: 'Chinese Yuan (Offshore)',
  CNY: 'Chinese Yuan',
  COP: 'Colombian Peso',
  CRC: 'Costa Rican Colón',
  CUC: 'Cuban Convertible Peso',
  CUP: 'Cuban Peso',
  CVE: 'Cape Verdean Escudo',
  CZK: 'Czech Republic Koruna',
  DJF: 'Djiboutian Franc',
  DKK: 'Danish Krone',
  DOP: 'Dominican Peso',
  DZD: 'Algerian Dinar',
  EGP: 'Egyptian Pound',
  ERN: 'Eritrean Nakfa',
  ETB: 'Ethiopian Birr',
  EUR: 'Euro',
  FJD: 'Fijian Dollar',
  FKP: 'Falkland Islands Pound',
  GBP: 'British Pound Sterling',
  GEL: 'Georgian Lari',
  GGP: 'Guernsey Pound',
  GHS: 'Ghanaian Cedi',
  GIP: 'Gibraltar Pound',
  GMD: 'Gambian Dalasi',
  GNF: 'Guinean Franc',
  GTQ: 'Guatemalan Quetzal',
  GYD: 'Guyanaese Dollar',
  HKD: 'Hong Kong Dollar',
  HNL: 'Honduran Lempira',
  HRK: 'Croatian Kuna',
  HTG: 'Haitian Gourde',
  HUF: 'Hungarian Forint',
  IDR: 'Indonesian Rupiah',
  ILS: 'Israeli New Sheqel',
  IMP: 'Manx pound',
  INR: 'Indian Rupee',
  IQD: 'Iraqi Dinar',
  IRR: 'Iranian Rial',
  ISK: 'Icelandic Króna',
  JEP: 'Jersey Pound',
  JMD: 'Jamaican Dollar',
  JOD: 'Jordanian Dinar',
  JPY: 'Japanese Yen',
  KES: 'Kenyan Shilling',
  KGS: 'Kyrgystani Som',
  KHR: 'Cambodian Riel',
  KMF: 'Comorian Franc',
  KPW: 'North Korean Won',
  KRW: 'South Korean Won',
  KWD: 'Kuwaiti Dinar',
  KYD: 'Cayman Islands Dollar',
  KZT: 'Kazakhstani Tenge',
  LAK: 'Laotian Kip',
  LBP: 'Lebanese Pound',
  LKR: 'Sri Lankan Rupee',
  LRD: 'Liberian Dollar',
  LSL: 'Lesotho Loti',
  LYD: 'Libyan Dinar',
  MAD: 'Moroccan Dirham',
  MDL: 'Moldovan Leu',
  MGA: 'Malagasy Ariary',
  MKD: 'Macedonian Denar',
  MMK: 'Myanma Kyat',
  MNT: 'Mongolian Tugrik',
  MOP: 'Macanese Pataca',
  MRU: 'Mauritanian Ouguiya',
  MUR: 'Mauritian Rupee',
  MVR: 'Maldivian Rufiyaa',
  MWK: 'Malawian Kwacha',
  MXN: 'Mexican Peso',
  MYR: 'Malaysian Ringgit',
  MZN: 'Mozambican Metical',
  NAD: 'Namibian Dollar',
  NGN: 'Nigerian Naira',
  NIO: 'Nicaraguan Córdoba',
  NOK: 'Norwegian Krone',
  NPR: 'Nepalese Rupee',
  NZD: 'New Zealand Dollar',
  OMR: 'Omani Rial',
  PAB: 'Panamanian Balboa',
  PEN: 'Peruvian Nuevo Sol',
  PGK: 'Papua New Guinean Kina',
  PHP: 'Philippine Peso',
  PKR: 'Pakistani Rupee',
  PLN: 'Polish Zloty',
  PYG: 'Paraguayan Guarani',
  QAR: 'Qatari Rial',
  RON: 'Romanian Leu',
  RSD: 'Serbian Dinar',
  RUB: 'Russian Ruble',
  RWF: 'Rwandan Franc',
  SAR: 'Saudi Riyal',
  SBD: 'Solomon Islands Dollar',
  SCR: 'Seychellois Rupee',
  SDG: 'Sudanese Pound',
  SEK: 'Swedish Krona',
  SGD: 'Singapore Dollar',
  SHP: 'Saint Helena Pound',
  SLL: 'Sierra Leonean Leone',
  SOS: 'Somali Shilling',
  SRD: 'Surinamese Dollar',
  SSP: 'South Sudanese Pound',
  STD: 'São Tomé and Príncipe Dobra (pre-2018)',
  STN: 'São Tomé and Príncipe Dobra',
  SVC: 'Salvadoran Colón',
  SYP: 'Syrian Pound',
  SZL: 'Swazi Lilangeni',
  THB: 'Thai Baht',
  TJS: 'Tajikistani Somoni',
  TMT: 'Turkmenistani Manat',
  TND: 'Tunisian Dinar',
  TOP: "Tongan Pa'anga",
  TRY: 'Turkish Lira',
  TTD: 'Trinidad and Tobago Dollar',
  TWD: 'New Taiwan Dollar',
  TZS: 'Tanzanian Shilling',
  UAH: 'Ukrainian Hryvnia',
  UGX: 'Ugandan Shilling',
  USD: 'United States Dollar',
  UYU: 'Uruguayan Peso',
  UZS: 'Uzbekistan Som',
  VEF: 'Venezuelan Bolívar Fuerte (Old)',
  VES: 'Venezuelan Bolívar Soberano',
  VND: 'Vietnamese Dong',
  VUV: 'Vanuatu Vatu',
  WST: 'Samoan Tala',
  XAF: 'CFA Franc BEAC',
  XAG: 'Silver Ounce',
  XAU: 'Gold Ounce',
  XCD: 'East Caribbean Dollar',
  XDR: 'Special Drawing Rights',
  XOF: 'CFA Franc BCEAO',
  XPD: 'Palladium Ounce',
  XPF: 'CFP Franc',
  XPT: 'Platinum Ounce',
  YER: 'Yemeni Rial',
  ZAR: 'South African Rand',
  ZMW: 'Zambian Kwacha',
  ZWL: 'Zimbabwean Dollar',
};

export const suggestions = {
  '': [],
  1: ['haine', 'incaltaminte', 'pantaloni', 'tricouri'],
  2: [
    'happy hour',
    'benzinarie',
    'ceai/cafea',
    'restaurant',
    'ingetata',
    'ciocolata',
    'parc',
    'wiskey + cola',
    'cinema',
  ],
  3: [
    'nr1',
    'fourchette',
    'kaufland',
    'lunch',
    'pegas',
    'apa',
    'inghetata',
    'straus/glovo food',
    'local',
    'linela',
  ],
  4: ['flori', 'birthday'],
  5: [
    'hartie igienica',
    'sapun',
    'praf de spalat',
    'scutece',
    'pasta de dinti',
    'sampon',
    'servetele',
  ],
  6: ['apartment rent', 'mortgage rate'],
  7: ['farmacie', 'stomatolog', 'pediatru'],
  8: ['haircut', 'cursor subscription', 'spotify subscription', 'chatgpt subscription', 'youtube premium subscription', 'ufc subscription', 'google drive storage'],
  9: [
    'benzina',
    'motorina',
    'car service',
    'lichid parbriz',
    'car wash',
    'taxi',
    'parcare',
  ],
  10: ['gaz', 'lumina', 'starnet', 'infocom', 'orange', 'infobon'],
  11: [],
  12: [],
  13: ['nunta', 'cumatrie'],
};

export const incomeSuggestions = [
  'salary',
  'bonus',
  'freelance',
  'overtime',
  'interest',
  'gift',
  'cashback',
  'sale',
  'loan',
  'partner apartment contribution',
];

export const notificationType = {
  SUCCESS: 'success',
  ERROR: 'error',
};

export const themeList: Record<string, { label: string; accent: string; bg: string }> = {
  'bondi-blue':           { label: 'Bondi blue',           accent: '#00c4c9', bg: '#111D29' },
  'maximum-green-yellow': { label: 'Maximum green yellow', accent: '#a8d44a', bg: '#13122d' },
  'carrot-orange':        { label: 'Carrot orange',        accent: '#f5a742', bg: '#111D29' },
  saffron:                { label: 'Saffron',              accent: '#f0cc4a', bg: '#13122d' },
  cadetblue:              { label: 'Cadet blue',           accent: '#7ec8ca', bg: '#111827' },
  'blue-pink-gradient':   { label: 'Blue pink gradient',   accent: '#9d8dd6', bg: '#13122d' },
  'pearl-aqua':           { label: 'Pearl aqua',           accent: '#8fe0d9', bg: '#13122d' },
  'cambridge-blue':       { label: 'Cambridge blue',       accent: '#b8d4b9', bg: '#111827' },
  'malachite-green':      { label: 'Malachite green',      accent: '#00DFA2', bg: '#111827' },
  'deep-space-indigo':    { label: 'Deep space indigo',    accent: '#8b91e0', bg: '#111D29' },
};
