# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        cache-dependency-path: test/yarn.lock
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
    - name: Build
      run: node test.js && cd test && CI=false && yarn && yarn build && cp build/index.html ../404.html
      env:
        TEST_VAR: ${{ secrets.TEST_VAR }}
    - name: Deploy
      run: |
        git checkout -b prod
        git fetch origin
        git branch -u origin/prod
        git status
        date > date.txt
        git config --global user.name $user_name
        git config --global user.email $user_email
        git add .
        git commit -m "Push built application"
        git push -f origin prod
      env:
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        TEST_VAR: ${{ secrets.TEST_VAR }}
