name: Ping the site to keep the server running.

on:
  schedule:
    # At every 30th minute.
    - cron:  '*/30 * * * *'

jobs:
  build:
    name: Trigger Site Ping
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: |
          curl -I https://dev-expenses-api.pantheonsite.io/github-action-ping
          curl -I https://dev-zepto-cms.pantheonsite.io/github-action-ping
